baseURL = 'https://www.arjenwiersma.nl'
languageCode = 'en-us'
title = 'Arjen Wiersma'

theme = "PaperMod"

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true

[params.homeInfoParams]
Title = 'Hi There! 👋'
Content = """
My name is Arjen and I am the Manager of Product Development and Chief Lecturer at [Hogeschool NOVI](https://www.novi.nl). I work on creating the most modern and relevant educational products that we can offer. Through stategic partnerships and attracting the most talented content developers we offer world class education to our students.
<br/><br/>
In my work as Chief Lecturer for Cybersecurity I focus on teaching students all there is to know about the technical side of Cyber Security. My main areas of expertise are Reverse Engineering, Infrastructure Security and Web Application Security.
<br/><br/>
Next to my work I am active as an Independent Hacker. I assist my customers in their journey to increase their security posture. I do this through advice, seminars and security assessments. I toot on the fediverse as [@credmp@fosstodon.org](https://fosstodon.org/@credmp).
<br/><br/>
I organize the Dutch meetup for [Hack The Box](https://www.hackthebox.com), for which I am the ambassador in The Netherlands. Each month, on the 3rd Wednesday, members of the Dutch cyber security community get together and have presentations, demos and discussion on wide ranging topics. Through this collaboration I have become an Ambassador for Hack The Box.
<br/><br/>
Find my longer form writings in the [Writing Category](/categories/writing/).
<br/><br/>
The views on this site are my own. 
"""


[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/credmp"

[[params.socialIcons]]
name = "github"
url = "https://github.com/credmp"
[[params.socialIcons]]
name = "mastodon"
url = "https://fosstodon.org/@credmp"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[markup.goldmark.renderer]
  unsafe = true


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-mocha'
    tabWidth = 4


# [module]
# [[module.mounts]]
#   source = 'content'
#   target = 'content'
# [[module.mounts]]
#   source = 'handbook'
#   target = 'content'
#   includeFiles = '/handbook/**'

[menu]
[[menu.main]]
 identifier = 'writings'
 name = '🚀 Long form writings'
 pre = "<i class='fa fa-heart'></i>"
 url = '/categories/writing/'
 weight = -110
