baseURL = 'https://www.arjenwiersma.nl'
languageCode = 'en-us'
title = 'Arjen Wiersma'
theme = 'typo'

# # # Disable tags
# disableKinds = ['taxonomy']

[taxonomies]
tag = 'tags'

[params]
# Home meta description
description = "A (edu)tech-oriented personal blog curated by Arjen Wiersma."

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content in markdown
homeIntroTitle = 'Hi! 👋'
homeIntroContent = """
My name is Arjen and I am the Manager of Product Development and Chief Lecturer at [Hogeschool NOVI](https://www.novi.nl). I work on creating the most modern and relevant educational products that we can offer. Through stategic partnerships and attracting the most talented content developers we offer world class education to our students.
<br/><br/>
In my work as Chief Lecturer for Cybersecurity I focus on teaching students all there is to know about the technical side of Cyber Security. My main areas of expertise are Reverse Engineering, Infrastructure Security and Web Application Security.
<br/><br/>
Next to my work I am active as an Independent Hacker. I assist my customers in their journey to increase their security posture. I do this through advice, seminars and security assessments. I toot on the fediverse as [@credmp@fosstodon.org](https://fosstodon.org/@credmp).
<br/><br/>
I used to organize the Dutch meetup for [Hack The Box](https://www.hackthebox.com), for which I was the ambassador in The Netherlands from 2020 up to June of 2024. Each month, on the 3rd Wednesday, members of the Dutch cyber security community got together and gave presentations, demos and discussion on wide ranging topics.
<br/><br/>
The views on this site are my own. 
"""

singleDateFormat = '2 Jan 2006'

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '02 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/credmp/"

[[params.social]]
name = "mastodon"
url = "https://fosstodon.org/@credmp"

[[params.social]]
name = "github"
url = "https://github.com/credmp"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "tags"
url = "/tags"


# Syntax highligth on code blocks
[markup]
[markup.highlight]
#style = 'bw'
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'bw'
tabWidth = 4

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

