baseURL = 'https://www.arjenwiersma.nl/'
languageCode = 'en-us'
title = "Arjen Wiersma"
copyright = 'Arjen Wiersma' # Used in the footer copyright mention.
enableRobotsTXT = false # IMPORTANT: set to true if you want to use the theme's genAI/LLM web crawler blocking feature.

[module]
  [[module.imports]]
    path = "github.com/michenriksen/hugo-theme-til"

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = 'Talks'
    pageRef = '/talks'
    weight = 15
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'Graph'
    pageRef = '/graph'
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[params]
  [params.author]
    name = 'Arjen Wiersma'
    email = ''

  [params.footer]
    creativeCommonsLicense = 'by_sa'

  [params.robotstxt]
    blockCC = false
    blockAI = false
