#+TITLE: Arjen Wiersma
#+SUBTITLE: Writings

I am the Chief Lecturer for Cyber Security at [[https://www.novi.nl][Hogeschool NOVI]]. In my work I focus teaching students all there is to know about the technical side of Cyber Security. My main areas of expertise are Reverse Engineering, Infrastructure Security and Web Application Security. The views on this site are my own.

Next to my work I am active as an Independent Hacker. I assist my customers in their journey to increase their security posture. I do this through advice, seminars and security assessments.

I run the meetup for [[https://www.hackthebox.eu][Hack The Box]] Netherlands. Each month, the 3rd Wednesday, members of the Dutch cyber security community get together and have presentations, demos and discussion on wide ranging topics.

* Latest writings
  :PROPERTIES:
  :HTML_CONTAINER_CLASS: post-list
  :END:

#+INCLUDE: posts/posts.org

Full list in the [[file:posts/archive.org][blog archive]].

* Public talks and presentations

From time to time I talk at conferences and meetups.

- Hack The Box University CTF :: I was one of the opening talks for the event. In my talk ([[https://youtu.be/3b2Xul3gu_8?t=3592][YouTube link]]) I explained how Hogeschool NOVI developed its Cyber Security program. I focused on the technical side of the curriculum and how it ties into the Hack The Box platform. 
- Just enough Reverse Engineering :: During the 2nd Hack The Box meetup I talked ([[https://www.youtube.com/watch?v=GXd9HIUPntE&list=PLJODoimT7es6K2jGS3GJIlnHih-htUlub&index=3][YouTube link]]) about the basics of reverse engineering, the phases of the proces and the tools you can use for it. It was an introductionary talk. 

* Projects/Code
  :PROPERTIES:
  :HTML_CONTAINER_CLASS: post-list
  :END:

- <2020-11-29 Sun> Released [[https://www.adventofctf.com][Advent of CTF]] on the world

* Write Ups
  :PROPERTIES:
  :HTML_CONTAINER_CLASS: post-list
  :END:

