#+TITLE: Reflecting on The Advent of CTF
#+subtitle: Hosting a month long CTF
#+options: toc:nil
#+DATE: <2021-01-20 Wed>

* The end of a month

On December 24 the last puzzle went live. It was quite an amazing experience. Over 500 people participated in the daily puzzles.

During the event several opportunities to give away prizes presented themselves. The CTF had 3 prizes to give away by [[https://www.hackthebox.eu][Hack The Box]] and an awesome Challenge Coin presented by [[https://www.novi.nl][NOVI Hogeschool]], my employer. Once the coins are available I will blog about them, for now you will just have to believe they are awesome!

During the last Hack The Box NL Meetup I gave a talk about the infrastructure and my experiences with hosting such a big event. The talk is linked below.

Some interesting posts I created along the way are linked below:

- [[./../../writeups/advent-of-ctf/stats/index.html][Statistics for the Top 20 finishers]] :: Every day I calculated the time the top 20 needed to finish the challenges. This is a good indicator for the complexity of the challenges.
- [[./../../writeups/advent-of-ctf/index.org][The write-ups]] :: Each challenge has its own write-up, including custom artwork for the challenge.

* The Talk

Included here is the talk I gave at the January meetup. It goes into detail about the infrastructure, the pitfalls of creating challenges and hosting an event that starts at 8am each day.

#+HTML: <iframe width="560" height="315" src="https://www.youtube.com/embed/FMXxMWFMOC8?start=160" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

* The code

I have put all the challenges up on [[https://github.com/adventofctf/2020][Github]] so you can run them yourself. They are based on docker containers, so the experience will be the same as during the event, minus the anti-cheat measures detailed in the video.

Go back to the [[../../index.org][homepage]].
